;;; matugen-theme.el --- Dynamic matugen theme for Doom Emacs -*- lexical-binding: t; -*-
(deftheme matugen "Dynamic theme generated by Matugen.")

(let ((bg "{{colors.background.default.hex}}")
      (fg "{{colors.on_surface.default.hex}}")
      (c0 "{{colors.primary.default.hex}}")
      (c1 "{{colors.secondary.default.hex}}")
      (c2 "{{colors.tertiary.default.hex}}"))
  (custom-theme-set-faces
   'matugen
   `(default ((t (:background ,bg :foreground ,fg))))
   `(region ((t (:background ,c1 :foreground ,bg))))
   `(hl-line ((t (:background "#1e1e1e"))))))

(provide-theme 'matugen)
